package org.dfir.harita.app.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.dfir.harita.app.model.dao.Isletme;
import org.dfir.harita.app.model.dao.Firsat;
import org.dfir.harita.app.model.dao.Musteri;
import org.dfir.harita.app.model.dao.Musteri_Isletme;
import org.dfir.harita.app.model.dao.Musteri_Firsat;
import org.dfir.harita.app.model.dao.Firsatlarim;

import org.dfir.harita.app.model.dao.IsletmeDao;
import org.dfir.harita.app.model.dao.FirsatDao;
import org.dfir.harita.app.model.dao.MusteriDao;
import org.dfir.harita.app.model.dao.Musteri_IsletmeDao;
import org.dfir.harita.app.model.dao.Musteri_FirsatDao;
import org.dfir.harita.app.model.dao.FirsatlarimDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig isletmeDaoConfig;
    private final DaoConfig firsatDaoConfig;
    private final DaoConfig musteriDaoConfig;
    private final DaoConfig musteri_IsletmeDaoConfig;
    private final DaoConfig musteri_FirsatDaoConfig;
    private final DaoConfig firsatlarimDaoConfig;

    private final IsletmeDao isletmeDao;
    private final FirsatDao firsatDao;
    private final MusteriDao musteriDao;
    private final Musteri_IsletmeDao musteri_IsletmeDao;
    private final Musteri_FirsatDao musteri_FirsatDao;
    private final FirsatlarimDao firsatlarimDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        isletmeDaoConfig = daoConfigMap.get(IsletmeDao.class).clone();
        isletmeDaoConfig.initIdentityScope(type);

        firsatDaoConfig = daoConfigMap.get(FirsatDao.class).clone();
        firsatDaoConfig.initIdentityScope(type);

        musteriDaoConfig = daoConfigMap.get(MusteriDao.class).clone();
        musteriDaoConfig.initIdentityScope(type);

        musteri_IsletmeDaoConfig = daoConfigMap.get(Musteri_IsletmeDao.class).clone();
        musteri_IsletmeDaoConfig.initIdentityScope(type);

        musteri_FirsatDaoConfig = daoConfigMap.get(Musteri_FirsatDao.class).clone();
        musteri_FirsatDaoConfig.initIdentityScope(type);

        firsatlarimDaoConfig = daoConfigMap.get(FirsatlarimDao.class).clone();
        firsatlarimDaoConfig.initIdentityScope(type);

        isletmeDao = new IsletmeDao(isletmeDaoConfig, this);
        firsatDao = new FirsatDao(firsatDaoConfig, this);
        musteriDao = new MusteriDao(musteriDaoConfig, this);
        musteri_IsletmeDao = new Musteri_IsletmeDao(musteri_IsletmeDaoConfig, this);
        musteri_FirsatDao = new Musteri_FirsatDao(musteri_FirsatDaoConfig, this);
        firsatlarimDao = new FirsatlarimDao(firsatlarimDaoConfig, this);

        registerDao(Isletme.class, isletmeDao);
        registerDao(Firsat.class, firsatDao);
        registerDao(Musteri.class, musteriDao);
        registerDao(Musteri_Isletme.class, musteri_IsletmeDao);
        registerDao(Musteri_Firsat.class, musteri_FirsatDao);
        registerDao(Firsatlarim.class, firsatlarimDao);
    }
    
    public void clear() {
        isletmeDaoConfig.getIdentityScope().clear();
        firsatDaoConfig.getIdentityScope().clear();
        musteriDaoConfig.getIdentityScope().clear();
        musteri_IsletmeDaoConfig.getIdentityScope().clear();
        musteri_FirsatDaoConfig.getIdentityScope().clear();
        firsatlarimDaoConfig.getIdentityScope().clear();
    }

    public IsletmeDao getIsletmeDao() {
        return isletmeDao;
    }

    public FirsatDao getFirsatDao() {
        return firsatDao;
    }

    public MusteriDao getMusteriDao() {
        return musteriDao;
    }

    public Musteri_IsletmeDao getMusteri_IsletmeDao() {
        return musteri_IsletmeDao;
    }

    public Musteri_FirsatDao getMusteri_FirsatDao() {
        return musteri_FirsatDao;
    }

    public FirsatlarimDao getFirsatlarimDao() {
        return firsatlarimDao;
    }

}
