package org.dfir.harita.app.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.dfir.harita.app.model.dao.Firsatlarim;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FIRSATLARIM.
*/
public class FirsatlarimDao extends AbstractDao<Firsatlarim, Long> {

    public static final String TABLENAME = "FIRSATLARIM";

    /**
     * Properties of entity Firsatlarim.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Firsat_id = new Property(1, Long.class, "firsat_id", false, "FIRSAT_ID");
        public final static Property Sure = new Property(2, Integer.class, "sure", false, "SURE");
        public final static Property Yararlanildi_mi = new Property(3, Boolean.class, "yararlanildi_mi", false, "YARARLANILDI_MI");
    };

    private DaoSession daoSession;

    private Query<Firsatlarim> firsat_FirsatlarimListesiQuery;

    public FirsatlarimDao(DaoConfig config) {
        super(config);
    }
    
    public FirsatlarimDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FIRSATLARIM' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'FIRSAT_ID' INTEGER," + // 1: firsat_id
                "'SURE' INTEGER," + // 2: sure
                "'YARARLANILDI_MI' INTEGER);"); // 3: yararlanildi_mi
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FIRSATLARIM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Firsatlarim entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long firsat_id = entity.getFirsat_id();
        if (firsat_id != null) {
            stmt.bindLong(2, firsat_id);
        }
 
        Integer sure = entity.getSure();
        if (sure != null) {
            stmt.bindLong(3, sure);
        }
 
        Boolean yararlanildi_mi = entity.getYararlanildi_mi();
        if (yararlanildi_mi != null) {
            stmt.bindLong(4, yararlanildi_mi ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(Firsatlarim entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Firsatlarim readEntity(Cursor cursor, int offset) {
        Firsatlarim entity = new Firsatlarim( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // firsat_id
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // sure
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // yararlanildi_mi
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Firsatlarim entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFirsat_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSure(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setYararlanildi_mi(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Firsatlarim entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Firsatlarim entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "firsatlarimListesi" to-many relationship of Firsat. */
    public List<Firsatlarim> _queryFirsat_FirsatlarimListesi(Long firsat_id) {
        synchronized (this) {
            if (firsat_FirsatlarimListesiQuery == null) {
                QueryBuilder<Firsatlarim> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Firsat_id.eq(null));
                firsat_FirsatlarimListesiQuery = queryBuilder.build();
            }
        }
        Query<Firsatlarim> query = firsat_FirsatlarimListesiQuery.forCurrentThread();
        query.setParameter(0, firsat_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFirsatDao().getAllColumns());
            builder.append(" FROM FIRSATLARIM T");
            builder.append(" LEFT JOIN FIRSAT T0 ON T.'FIRSAT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Firsatlarim loadCurrentDeep(Cursor cursor, boolean lock) {
        Firsatlarim entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Firsat firsat = loadCurrentOther(daoSession.getFirsatDao(), cursor, offset);
        entity.setFirsat(firsat);

        return entity;    
    }

    public Firsatlarim loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Firsatlarim> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Firsatlarim> list = new ArrayList<Firsatlarim>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Firsatlarim> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Firsatlarim> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
