package org.dfir.harita.app.model.dao;

import org.dfir.harita.app.model.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSTERI__FIRSAT.
 */
public class Musteri_Firsat {

    private Long id;
    private Long musteri_id;
    private Long firsat_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient Musteri_FirsatDao myDao;

    private Musteri musteri;
    private Long musteri__resolvedKey;

    private Firsat firsat;
    private Long firsat__resolvedKey;


    public Musteri_Firsat() {
    }

    public Musteri_Firsat(Long id) {
        this.id = id;
    }

    public Musteri_Firsat(Long id, Long musteri_id, Long firsat_id) {
        this.id = id;
        this.musteri_id = musteri_id;
        this.firsat_id = firsat_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMusteri_FirsatDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMusteri_id() {
        return musteri_id;
    }

    public void setMusteri_id(Long musteri_id) {
        this.musteri_id = musteri_id;
    }

    public Long getFirsat_id() {
        return firsat_id;
    }

    public void setFirsat_id(Long firsat_id) {
        this.firsat_id = firsat_id;
    }

    /** To-one relationship, resolved on first access. */
    public Musteri getMusteri() {
        Long __key = this.musteri_id;
        if (musteri__resolvedKey == null || !musteri__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MusteriDao targetDao = daoSession.getMusteriDao();
            Musteri musteriNew = targetDao.load(__key);
            synchronized (this) {
                musteri = musteriNew;
            	musteri__resolvedKey = __key;
            }
        }
        return musteri;
    }

    public void setMusteri(Musteri musteri) {
        synchronized (this) {
            this.musteri = musteri;
            musteri_id = musteri == null ? null : musteri.getId();
            musteri__resolvedKey = musteri_id;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Firsat getFirsat() {
        Long __key = this.firsat_id;
        if (firsat__resolvedKey == null || !firsat__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            FirsatDao targetDao = daoSession.getFirsatDao();
            Firsat firsatNew = targetDao.load(__key);
            synchronized (this) {
                firsat = firsatNew;
            	firsat__resolvedKey = __key;
            }
        }
        return firsat;
    }

    public void setFirsat(Firsat firsat) {
        synchronized (this) {
            this.firsat = firsat;
            firsat_id = firsat == null ? null : firsat.getId();
            firsat__resolvedKey = firsat_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
