package org.dfir.harita.app.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.dfir.harita.app.model.dao.Musteri_Isletme;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MUSTERI__ISLETME.
*/
public class Musteri_IsletmeDao extends AbstractDao<Musteri_Isletme, Long> {

    public static final String TABLENAME = "MUSTERI__ISLETME";

    /**
     * Properties of entity Musteri_Isletme.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Musteri_id = new Property(1, Long.class, "musteri_id", false, "MUSTERI_ID");
        public final static Property Isletme_id = new Property(2, Long.class, "isletme_id", false, "ISLETME_ID");
    };

    private DaoSession daoSession;

    private Query<Musteri_Isletme> isletme_MusteriIsletmelerQuery;
    private Query<Musteri_Isletme> musteri_MusteriIsletmelerQuery;

    public Musteri_IsletmeDao(DaoConfig config) {
        super(config);
    }
    
    public Musteri_IsletmeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MUSTERI__ISLETME' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MUSTERI_ID' INTEGER," + // 1: musteri_id
                "'ISLETME_ID' INTEGER);"); // 2: isletme_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MUSTERI__ISLETME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Musteri_Isletme entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long musteri_id = entity.getMusteri_id();
        if (musteri_id != null) {
            stmt.bindLong(2, musteri_id);
        }
 
        Long isletme_id = entity.getIsletme_id();
        if (isletme_id != null) {
            stmt.bindLong(3, isletme_id);
        }
    }

    @Override
    protected void attachEntity(Musteri_Isletme entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Musteri_Isletme readEntity(Cursor cursor, int offset) {
        Musteri_Isletme entity = new Musteri_Isletme( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // musteri_id
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // isletme_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Musteri_Isletme entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMusteri_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIsletme_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Musteri_Isletme entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Musteri_Isletme entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "musteriIsletmeler" to-many relationship of Isletme. */
    public List<Musteri_Isletme> _queryIsletme_MusteriIsletmeler(Long isletme_id) {
        synchronized (this) {
            if (isletme_MusteriIsletmelerQuery == null) {
                QueryBuilder<Musteri_Isletme> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Isletme_id.eq(null));
                isletme_MusteriIsletmelerQuery = queryBuilder.build();
            }
        }
        Query<Musteri_Isletme> query = isletme_MusteriIsletmelerQuery.forCurrentThread();
        query.setParameter(0, isletme_id);
        return query.list();
    }

    /** Internal query to resolve the "musteriIsletmeler" to-many relationship of Musteri. */
    public List<Musteri_Isletme> _queryMusteri_MusteriIsletmeler(Long musteri_id) {
        synchronized (this) {
            if (musteri_MusteriIsletmelerQuery == null) {
                QueryBuilder<Musteri_Isletme> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Musteri_id.eq(null));
                musteri_MusteriIsletmelerQuery = queryBuilder.build();
            }
        }
        Query<Musteri_Isletme> query = musteri_MusteriIsletmelerQuery.forCurrentThread();
        query.setParameter(0, musteri_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getIsletmeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getMusteriDao().getAllColumns());
            builder.append(" FROM MUSTERI__ISLETME T");
            builder.append(" LEFT JOIN ISLETME T0 ON T.'ISLETME_ID'=T0.'_id'");
            builder.append(" LEFT JOIN MUSTERI T1 ON T.'MUSTERI_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Musteri_Isletme loadCurrentDeep(Cursor cursor, boolean lock) {
        Musteri_Isletme entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Isletme isletme = loadCurrentOther(daoSession.getIsletmeDao(), cursor, offset);
        entity.setIsletme(isletme);
        offset += daoSession.getIsletmeDao().getAllColumns().length;

        Musteri musteri = loadCurrentOther(daoSession.getMusteriDao(), cursor, offset);
        entity.setMusteri(musteri);

        return entity;    
    }

    public Musteri_Isletme loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Musteri_Isletme> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Musteri_Isletme> list = new ArrayList<Musteri_Isletme>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Musteri_Isletme> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Musteri_Isletme> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
